from .iterrestrial import ITerrestrial
from .ifreshwater import IFreshwater
from .iaquatic import IAquatic
from .iforest import IForest
from .igrassland import IGrassland
from .imountain import IMountain
from .isaltwater import ISaltwater
from ..identifiable import Identifiable
from .contains_animals import IContainsAnimals
from .contains_plants import IContainsPlants
